# Generated by Django 5.1.15 on 2026-02-07 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0002_add_project"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="document",
            new_name="ingestion_d_tenant__8145c1_idx",
            old_name="ingestion_d_tenant_proj_st_idx",
        ),
    ]
