# Generated by Django 5.1.15 on 2026-03-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connectors", "0002_add_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectorconfig",
            name="encrypted_secret",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Fernet-encrypted secret (set via set_secret, read via get_secret)",
            ),
        ),
    ]
