# Generated by Django 5.1.15 on 2026-04-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0003_add_elasticsearch_connector_type'),
        ('connectors', '0003_add_encrypted_secret'),
    ]

    operations = [
    ]
