# Generated by Django 5.1.15 on 2026-02-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_backfill_default_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantmembership",
            name="language",
            field=models.CharField(
                choices=[("fr", "Français"), ("en", "English")],
                default="fr",
                max_length=10,
            ),
        ),
    ]
