# Generated by Django 5.1.15 on 2026-02-10 18:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0004_add_language_to_membership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("user_invited", "Utilisateur invité"),
                            ("user_removed", "Utilisateur retiré"),
                            ("role_changed", "Rôle modifié"),
                            ("project_created", "Projet créé"),
                            ("project_deleted", "Projet supprimé"),
                            ("tenant_created", "Espace créé"),
                            ("analysis_deleted", "Analyse supprimée"),
                            ("connector_deleted", "Connecteur supprimé"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("target_id", models.CharField(blank=True, default="", max_length=200)),
                (
                    "target_label",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"],
                        name="tenants_aud_tenant__40f760_idx",
                    ),
                    models.Index(
                        fields=["action"], name="tenants_aud_action_d5e708_idx"
                    ),
                ],
            },
        ),
    ]
