# Generated by Django 5.1.15 on 2026-02-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="tools",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
