# Generated by Django 5.1.15 on 2026-09-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_add_chatconfig_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="graph_trace",
            field=models.JSONField(
                blank=True, default=dict, help_text="Relations du graphe ayant étayé la réponse"
            ),
        ),
    ]
