# Generated by Django 5.1.15 on 2026-02-07 11:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ingestion", "__first__"),
        ("tenants", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "En attente"),
                            ("running", "En cours"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "current_phase",
                    models.CharField(
                        choices=[
                            ("duplicates", "Détection des doublons"),
                            ("claims", "Extraction des affirmations"),
                            ("contradictions", "Détection des contradictions"),
                            ("clustering", "Clustering thématique"),
                            ("gaps", "Détection des lacunes"),
                            ("tree", "Index arborescent"),
                            ("done", "Terminé"),
                        ],
                        default="duplicates",
                        max_length=20,
                    ),
                ),
                ("progress_pct", models.PositiveIntegerField(default=0)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=500)),
                ("predicate", models.CharField(max_length=500)),
                ("object_value", models.CharField(max_length=1000)),
                (
                    "qualifiers",
                    models.JSONField(
                        default=dict,
                        help_text="Additional qualifiers (date, version, scope)",
                    ),
                ),
                (
                    "claim_date",
                    models.DateField(blank=True, help_text="Date the claim pertains to", null=True),
                ),
                ("raw_text", models.TextField(help_text="Original passage text")),
                ("has_embedding", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="ingestion.documentchunk",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="ingestion.document",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContradictionPair",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("contradiction", "Contradiction"),
                            ("outdated", "Obsolète"),
                            ("entailment", "Implication"),
                            ("unrelated", "Sans rapport"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("high", "Élevée"),
                            ("medium", "Moyenne"),
                            ("low", "Faible"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(help_text="LLM confidence in this classification"),
                ),
                (
                    "evidence",
                    models.TextField(help_text="LLM explanation with citations"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contradictions",
                        to="analysis.analysisjob",
                    ),
                ),
                (
                    "authoritative_claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authoritative_for",
                        to="analysis.claim",
                    ),
                ),
                (
                    "claim_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contradiction_pairs_a",
                        to="analysis.claim",
                    ),
                ),
                (
                    "claim_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contradiction_pairs_b",
                        to="analysis.claim",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence"],
            },
        ),
        migrations.CreateModel(
            name="DuplicateGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recommended_action",
                    models.CharField(
                        choices=[
                            ("merge", "Fusionner"),
                            ("delete_older", "Supprimer l'ancien"),
                            ("review", "Vérification manuelle"),
                            ("keep", "Conserver les deux (liés, pas doublons)"),
                        ],
                        default="review",
                        max_length=20,
                    ),
                ),
                ("rationale", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_groups",
                        to="analysis.analysisjob",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DuplicatePair",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "semantic_score",
                    models.FloatField(help_text="Cosine similarity of document embeddings"),
                ),
                (
                    "lexical_score",
                    models.FloatField(help_text="MinHash Jaccard similarity"),
                ),
                (
                    "metadata_score",
                    models.FloatField(help_text="Title/path/author similarity"),
                ),
                ("combined_score", models.FloatField(help_text="Weighted combination")),
                ("verified", models.BooleanField(default=False)),
                (
                    "verification_result",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="duplicate / related / unrelated",
                        max_length=20,
                    ),
                ),
                ("verification_confidence", models.FloatField(blank=True, null=True)),
                (
                    "verification_evidence",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="LLM explanation of why this is/isn't a duplicate",
                    ),
                ),
                (
                    "evidence_chunks_a",
                    models.JSONField(default=list, help_text="Chunk IDs and snippets from doc A"),
                ),
                (
                    "evidence_chunks_b",
                    models.JSONField(default=list, help_text="Chunk IDs and snippets from doc B"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doc_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dup_pairs_a",
                        to="ingestion.document",
                    ),
                ),
                (
                    "doc_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dup_pairs_b",
                        to="ingestion.document",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairs",
                        to="analysis.duplicategroup",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-combined_score"],
            },
        ),
        migrations.CreateModel(
            name="TopicCluster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text="LLM-generated cluster label", max_length=500),
                ),
                (
                    "summary",
                    models.TextField(blank=True, default="", help_text="LLM-generated summary"),
                ),
                (
                    "key_concepts",
                    models.JSONField(default=list, help_text="LLM-extracted concept list"),
                ),
                (
                    "content_purpose",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="One-line purpose of this cluster's content",
                        max_length=500,
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(default=0, help_text="Hierarchy level (0 = top)"),
                ),
                ("doc_count", models.PositiveIntegerField(default=0)),
                ("chunk_count", models.PositiveIntegerField(default=0)),
                ("centroid_x", models.FloatField(blank=True, null=True)),
                ("centroid_y", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clusters",
                        to="analysis.analysisjob",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="analysis.topiccluster",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["level", "label"],
            },
        ),
        migrations.CreateModel(
            name="GapReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gap_type",
                    models.CharField(
                        choices=[
                            ("missing_topic", "Sujet manquant"),
                            ("low_coverage", "Faible couverture"),
                            ("stale_area", "Zone obsolète"),
                            ("orphan_topic", "Sujet orphelin"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Suggested topic/document title", max_length=500),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Why this gap was detected and what should be documented"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("high", "Élevée"),
                            ("medium", "Moyenne"),
                            ("low", "Faible"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "coverage_score",
                    models.FloatField(
                        blank=True,
                        help_text="0-1 score of how well this topic is covered (lower = bigger gap)",
                        null=True,
                    ),
                ),
                (
                    "evidence",
                    models.JSONField(
                        default=dict,
                        help_text="Questions that couldn't be answered, adjacent clusters, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gaps",
                        to="analysis.analysisjob",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "related_cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="analysis.topiccluster",
                    ),
                ),
            ],
            options={
                "ordering": ["coverage_score", "-severity"],
            },
        ),
        migrations.CreateModel(
            name="ClusterMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("similarity_to_centroid", models.FloatField(default=0.0)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_memberships",
                        to="ingestion.documentchunk",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_memberships",
                        to="ingestion.document",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="analysis.topiccluster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TreeNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=500)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("category", "Catégorie"),
                            ("cluster", "Cluster"),
                            ("document", "Document"),
                            ("section", "Section"),
                        ],
                        max_length=20,
                    ),
                ),
                ("level", models.PositiveIntegerField(default=0)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "analysis_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tree_nodes",
                        to="analysis.analysisjob",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="analysis.topiccluster",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.document",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="analysis.treenode",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["level", "sort_order"],
            },
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(fields=["tenant", "subject"], name="analysis_cl_tenant__05b49b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="duplicatepair",
            unique_together={("group", "doc_a", "doc_b")},
        ),
        migrations.AlterUniqueTogether(
            name="clustermembership",
            unique_together={("cluster", "chunk")},
        ),
    ]
