# Generated by Django 5.1.15 on 2026-02-07 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_add_project"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="claim",
            new_name="analysis_cl_tenant__de3d67_idx",
            old_name="analysis_cl_tenant_proj_subj_idx",
        ),
    ]
