# Generated by Django 5.1.15 on 2026-02-08 08:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "analysis",
            "0003_rename_analysis_cl_tenant_proj_subj_idx_analysis_cl_tenant__de3d67_idx",
        ),
        ("tenants", "0003_backfill_default_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "En attente"),
                            ("running", "En cours"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "current_axis",
                    models.CharField(
                        choices=[
                            ("hygiene", "Hygiène du corpus"),
                            ("structure", "Structure RAG"),
                            ("coverage", "Couverture sémantique"),
                            ("coherence", "Cohérence interne"),
                            ("retrievability", "Retrievability"),
                            ("governance", "Gouvernance & metadata"),
                            ("done", "Terminé"),
                        ],
                        default="hygiene",
                        max_length=20,
                    ),
                ),
                ("progress_pct", models.PositiveIntegerField(default=0)),
                (
                    "overall_score",
                    models.FloatField(blank=True, help_text="0-100 weighted score", null=True),
                ),
                (
                    "overall_grade",
                    models.CharField(blank=True, default="", help_text="A-E grade", max_length=1),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.project",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditAxisResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "axis",
                    models.CharField(
                        choices=[
                            ("hygiene", "Hygiène du corpus"),
                            ("structure", "Structure RAG"),
                            ("coverage", "Couverture sémantique"),
                            ("coherence", "Cohérence interne"),
                            ("retrievability", "Retrievability"),
                            ("governance", "Gouvernance & metadata"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.FloatField(help_text="0-100 axis score")),
                (
                    "metrics",
                    models.JSONField(default=dict, help_text="Key metrics for this axis"),
                ),
                (
                    "chart_data",
                    models.JSONField(default=dict, help_text="Pre-computed data for D3.js charts"),
                ),
                (
                    "details",
                    models.JSONField(
                        default=dict, help_text="Detailed findings and item-level data"
                    ),
                ),
                ("duration_seconds", models.FloatField(default=0.0)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.project",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "audit_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="axis_results",
                        to="analysis.auditjob",
                    ),
                ),
            ],
            options={
                "ordering": ["axis"],
                "unique_together": {("audit_job", "axis")},
            },
        ),
    ]
