# Generated by Django 5.1.15 on 2026-02-09 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0004_auditjob_auditaxisresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisjob",
            name="includes_audit",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="auditjob",
            name="analysis_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_jobs",
                to="analysis.analysisjob",
            ),
        ),
        migrations.AlterField(
            model_name="analysisjob",
            name="current_phase",
            field=models.CharField(
                choices=[
                    ("duplicates", "Détection des doublons"),
                    ("claims", "Extraction des affirmations"),
                    ("contradictions", "Détection des contradictions"),
                    ("clustering", "Clustering thématique"),
                    ("gaps", "Détection des lacunes"),
                    ("tree", "Index arborescent"),
                    ("audit_hygiene", "Audit : Hygiène"),
                    ("audit_structure", "Audit : Structure"),
                    ("audit_coverage", "Audit : Couverture"),
                    ("audit_coherence", "Audit : Cohérence"),
                    ("audit_retrievability", "Audit : Retrievability"),
                    ("audit_governance", "Audit : Gouvernance"),
                    ("done", "Terminé"),
                ],
                default="duplicates",
                max_length=30,
            ),
        ),
    ]
