# Generated by Django 5.1.15 on 2026-02-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0005_analysisjob_includes_audit_auditjob_analysis_job_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisjob",
            name="current_phase",
            field=models.CharField(
                choices=[
                    ("duplicates", "Détection des doublons"),
                    ("claims", "Extraction des affirmations"),
                    ("semantic_graph", "Graphe sémantique"),
                    ("contradictions", "Détection des contradictions"),
                    ("clustering", "Clustering thématique"),
                    ("gaps", "Détection des lacunes"),
                    ("tree", "Index arborescent"),
                    ("audit_hygiene", "Audit : Hygiène"),
                    ("audit_structure", "Audit : Structure"),
                    ("audit_coverage", "Audit : Couverture"),
                    ("audit_coherence", "Audit : Cohérence"),
                    ("audit_retrievability", "Audit : Retrievability"),
                    ("audit_governance", "Audit : Gouvernance"),
                    ("done", "Terminé"),
                ],
                default="duplicates",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="gapreport",
            name="gap_type",
            field=models.CharField(
                choices=[
                    ("missing_topic", "Sujet manquant"),
                    ("low_coverage", "Faible couverture"),
                    ("stale_area", "Zone obsolète"),
                    ("orphan_topic", "Sujet orphelin"),
                    ("weak_bridge", "Pont fragile"),
                    ("concept_island", "Îlot conceptuel"),
                ],
                max_length=20,
            ),
        ),
    ]
