# Generated by Django 5.1.15 on 2026-02-09 17:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0006_alter_analysisjob_current_phase_and_more"),
        ("tenants", "0003_backfill_default_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineTrace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_llm_calls", models.PositiveIntegerField(default=0)),
                ("total_embed_calls", models.PositiveIntegerField(default=0)),
                ("total_search_calls", models.PositiveIntegerField(default=0)),
                ("total_prompt_tokens", models.PositiveIntegerField(default=0)),
                ("total_completion_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                ("total_duration_seconds", models.FloatField(default=0.0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trace",
                        to="analysis.analysisjob",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.project",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PhaseTrace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phase_key", models.CharField(max_length=30)),
                ("phase_label", models.CharField(max_length=100)),
                ("llm_calls", models.PositiveIntegerField(default=0)),
                ("embed_calls", models.PositiveIntegerField(default=0)),
                ("search_calls", models.PositiveIntegerField(default=0)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                ("items_in", models.PositiveIntegerField(default=0)),
                ("items_out", models.PositiveIntegerField(default=0)),
                ("duration_seconds", models.FloatField(default=0.0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "En cours"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                            ("skipped", "Ignoré"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.project",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "pipeline_trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="analysis.pipelinetrace",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "unique_together": {("pipeline_trace", "phase_key")},
            },
        ),
        migrations.CreateModel(
            name="TraceEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("llm_chat", "LLM Chat"),
                            ("llm_chat_concurrent", "LLM Chat Concurrent"),
                            ("llm_chat_batch", "LLM Chat Batch"),
                            ("llm_embed", "Embedding"),
                            ("vec_search", "Vector Search"),
                            ("vec_search_claims", "Claims Search"),
                            ("vec_upsert", "Vector Upsert"),
                        ],
                        max_length=25,
                    ),
                ),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                ("item_count", models.PositiveIntegerField(default=0)),
                ("result_count", models.PositiveIntegerField(default=0)),
                ("duration_seconds", models.FloatField(default=0.0)),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "phase_trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="analysis.phasetrace",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["phase_trace", "event_type"],
                        name="analysis_tr_phase_t_27fd0c_idx",
                    )
                ],
            },
        ),
    ]
