# Generated by Django 5.1.15 on 2026-02-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0007_pipelinetrace_phasetrace_traceevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisjob",
            name="phase_detail",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
