# Generated by Django 5.1.15 on 2026-02-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0008_analysisjob_phase_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisjob",
            name="config_overrides",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-job analysis config overrides (merged on top of config.yaml defaults)",
            ),
        ),
    ]
