# Generated by Django 5.1.15 on 2026-02-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0009_analysisjob_config_overrides"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "En attente"),
                    ("running", "En cours"),
                    ("completed", "Terminé"),
                    ("failed", "Échoué"),
                    ("cancelled", "Annulé"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
    ]
