# Generated by Django 5.1.15 on 2026-02-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0011_add_contradiction_resolution"),
    ]

    operations = [
        migrations.AddField(
            model_name="gapreport",
            name="resolution",
            field=models.CharField(
                blank=True,
                choices=[("", "Non traité"), ("resolved", "Traité"), ("kept", "Conservé")],
                default="",
                max_length=10,
            ),
        ),
    ]
