# Generated by Django 5.1.15 on 2026-02-24 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_add_gap_resolution'),
        ('ingestion', '0003_rename_ingestion_d_tenant_proj_st_idx_ingestion_d_tenant__8145c1_idx'),
        ('tenants', '0005_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisjob',
            name='current_phase',
            field=models.CharField(choices=[('duplicates', 'Détection des doublons'), ('claims', 'Extraction des affirmations'), ('semantic_graph', 'Graphe sémantique'), ('contradictions', 'Détection des contradictions'), ('clustering', 'Clustering thématique'), ('gaps', 'Détection des lacunes'), ('tree', 'Index arborescent'), ('hallucination', "Détection des risques d'hallucination"), ('audit_hygiene', 'Audit : Hygiène'), ('audit_structure', 'Audit : Structure'), ('audit_coverage', 'Audit : Couverture'), ('audit_coherence', 'Audit : Cohérence'), ('audit_retrievability', 'Audit : Retrievability'), ('audit_governance', 'Audit : Gouvernance'), ('done', 'Terminé')], default='duplicates', max_length=30),
        ),
        migrations.CreateModel(
            name='HallucinationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_type', models.CharField(choices=[('undefined_acronym', 'Acronyme non défini'), ('ambiguous_acronym', 'Acronyme ambigu'), ('conflicting_acronym', 'Acronyme contradictoire'), ('jargon_no_context', 'Jargon sans contexte'), ('hedging_language', 'Langage incertain'), ('implicit_knowledge', 'Connaissance implicite')], max_length=25)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('high', 'Élevée'), ('medium', 'Moyenne'), ('low', 'Faible')], default='medium', max_length=10)),
                ('resolution', models.CharField(blank=True, choices=[('', 'Non traité'), ('resolved', 'Traité'), ('kept', 'Conservé')], default='', max_length=10)),
                ('term', models.CharField(blank=True, default='', max_length=200)),
                ('expansions', models.JSONField(default=list, help_text='List of known expansions with document references')),
                ('doc_count', models.PositiveIntegerField(default=0, help_text='Number of documents affected')),
                ('risk_score', models.FloatField(default=0.0, help_text='0-1 hallucination risk score (higher = more risky)')),
                ('evidence', models.JSONField(default=dict, help_text='Contextual evidence: passages, locations, conflicting definitions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallucination_reports', to='analysis.analysisjob')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hallucination_reports', to='ingestion.document')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-risk_score', 'severity'],
            },
        ),
    ]
