# Generated by Django 5.1.15 on 2026-09-04 12:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0013_hallucination_report"),
        ("ingestion", "0003_rename_ingestion_d_tenant_proj_st_idx_ingestion_d_tenant__8145c1_idx"),
        ("tenants", "0007_create_cache_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisjob",
            name="current_phase",
            field=models.CharField(
                choices=[
                    ("duplicates", "Détection des doublons"),
                    ("claims", "Extraction des affirmations"),
                    ("semantic_graph", "Graphe sémantique"),
                    ("contradictions", "Détection des contradictions"),
                    ("clustering", "Clustering thématique"),
                    ("knowledge_graph", "Graphe de connaissances"),
                    ("gaps", "Détection des lacunes"),
                    ("tree", "Index arborescent"),
                    ("hallucination", "Détection des risques d'hallucination"),
                    ("audit_hygiene", "Audit : Hygiène"),
                    ("audit_structure", "Audit : Structure"),
                    ("audit_coverage", "Audit : Couverture"),
                    ("audit_coherence", "Audit : Cohérence"),
                    ("audit_retrievability", "Audit : Retrievability"),
                    ("audit_governance", "Audit : Gouvernance"),
                    ("done", "Terminé"),
                ],
                default="duplicates",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="KnowledgeGraphRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("extract", "Extraction LLM dédiée"),
                            ("hybrid", "Extraction + affirmations"),
                            ("claims", "Affirmations existantes"),
                        ],
                        default="extract",
                        max_length=10,
                    ),
                ),
                (
                    "config_snapshot",
                    models.JSONField(
                        blank=True, default=dict, help_text="Effective config used for this build"
                    ),
                ),
                ("entity_count", models.PositiveIntegerField(default=0)),
                ("relation_count", models.PositiveIntegerField(default=0)),
                ("inferred_count", models.PositiveIntegerField(default=0)),
                ("cluster_count", models.PositiveIntegerField(default=0)),
                (
                    "bridge_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Entities appearing in more than one cluster"
                    ),
                ),
                ("duration_seconds", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kg_runs",
                        to="analysis.analysisjob",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.project",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KGEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "canonical",
                    models.CharField(
                        help_text="Normalised form, used for matching", max_length=300
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display form: most frequent variant", max_length=300
                    ),
                ),
                (
                    "aliases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Absorbed variants — makes standardisation auditable",
                    ),
                ),
                (
                    "search_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Label + aliases, normalised. SQLite cannot index inside a JSONField.",
                        max_length=1000,
                    ),
                ),
                (
                    "frequency",
                    models.PositiveIntegerField(default=0, help_text="Occurrences across triples"),
                ),
                ("degree", models.PositiveIntegerField(default=0)),
                (
                    "centrality",
                    models.FloatField(
                        default=0.0, help_text="Normalised betweenness; drives node size"
                    ),
                ),
                ("doc_count", models.PositiveIntegerField(default=0)),
                (
                    "cluster_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of clusters this entity appears in; > 1 means bridge",
                    ),
                ),
                (
                    "pos_x",
                    models.FloatField(default=0.0, help_text="Layout precomputed at build time"),
                ),
                ("pos_y", models.FloatField(default=0.0)),
                (
                    "main_cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kg_entities",
                        to="analysis.topiccluster",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.project",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="analysis.knowledgegraphrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-centrality"],
            },
        ),
        migrations.CreateModel(
            name="KGRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "predicate",
                    models.CharField(help_text="Normalised, 3 words at most", max_length=120),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=1.0, help_text="Number of triples merged into this edge"
                    ),
                ),
                ("confidence", models.FloatField(default=1.0)),
                ("inferred", models.BooleanField(default=False)),
                (
                    "inference_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Constatée"),
                            ("transitive", "Transitive"),
                            ("cross_cluster", "Entre clusters"),
                            ("within_cluster", "Dans un cluster"),
                            ("lexical", "Similarité lexicale"),
                        ],
                        default="",
                        max_length=15,
                    ),
                ),
                (
                    "evidence",
                    models.JSONField(blank=True, default=list, help_text="Up to 3 source snippets"),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kg_relations",
                        to="analysis.topiccluster",
                    ),
                ),
                (
                    "documents",
                    models.ManyToManyField(
                        blank=True, related_name="kg_relations", to="ingestion.document"
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_in",
                        to="analysis.kgentity",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.project",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_out",
                        to="analysis.kgentity",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations",
                        to="analysis.knowledgegraphrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["run", "predicate"], name="analysis_kg_run_id_485b1d_idx"),
                    models.Index(fields=["run", "inferred"], name="analysis_kg_run_id_ffd415_idx"),
                ],
                "unique_together": {("run", "subject", "object", "predicate")},
            },
        ),
        migrations.AddIndex(
            model_name="kgentity",
            index=models.Index(
                fields=["run", "main_cluster"], name="analysis_kg_run_id_d614e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kgentity",
            index=models.Index(fields=["run", "-centrality"], name="analysis_kg_run_id_046601_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="kgentity",
            unique_together={("run", "canonical")},
        ),
    ]
